version: '3.1'
services:
  mysql:
    image: mysql:8.0.18
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'