version: '3.1'
services:
  node-app:
    image: oliver/node-app:V1
    build:
      context: ./gate-simulator/.
    ports:
      - '9999:9999'
  mysql:
    image: mysql:8.0.18
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'