version: '3.1'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3306:3306"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: jdbc:mysql://localhost:3306/app
  postgres:
    image: mysql:8.0.18
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
